name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Copy Files to Deployment
        run: 'Xcopy /e /i /y * C:\Deployment\'
      - name: Run Tosca Tests
        run: ./RunToscaTests.bat
      - name: Attach the report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: Results.xml
          path: 'C:\temp\Result.xml'
      - name: Copy output from Tosca tests to local repo
        run: >-
          Xcopy /e /i /y C:\temp\DEX\DEXResults\Result.xml
          C:\actions-runner\_work\Sriram_Demo\Sriram_Demo
      - name: Test Reporter
        uses: dorny/test-reporter@v1.4.3
        with:
          name: Test
          path: Result.xml
          reporter: java-junit
