name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy Files to Deployment
        run: xcopy /e /i /y * C:\Deployment\

      - name: Run Tosca Tests
        run: C:\temp\RunToscaTest.bat

      - name: Attach the report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Result.xml
          path: C:\temp\DEX\DEXResults\result.xml

      - name: Copy output from Tosca tests to local repo
        run: |
          xcopy /e /i /y C:\temp\DEX\DEXResults\result.xml C:\Users\Administrator\actions-runner\actions-runner\_work\DemoRep\DemoRep\

      - name: Test Reporter
        uses: dorny/test-reporter@v2
        with:
          name: ToscaTestResults
          path: C:\temp\DEX\DEXResults\result.xml
          reporter: java-junit
