# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run.

on:

# Triggers the workflow on push or pull request events but only for the main branch

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # This is on prep for a full E2E demo using the DevOps Tricentis Server
      - name: Copy Files to Deployment
      	run: Xcopy /e /i /y * C:\Deployment\
      # Execute Tosca tests, the Powershell script is in the repo
      - name: RunToscaTests
      	run: ./RunToscaTests.ps1
	# Attach teh report to the run
	- name: Attach the report
	if: always()
	uses: actions/upload-artifact@v1
	with:
	  name: Results.xml
	  path: C:\temp\Result.xml
      # Publish Unit Test Results to github
      - name: Copy output from Tosca tests to local repo
	run: Xcopy /e /i /y C:\temp\Result.xml C:\actions-runner\_work\Bernhard_Klemm_Demo\Bernhard_Klemm_Demo
      - name: Test Reporter
	uses: dorny/test-reporter@v1.4.3
	with:
	name: Test
	  # Coma separated list of paths to test results
	path: Result.xml
	reporter: java-junit
